### ISSUE TITLE
feature request: quiet mode for version controlled bib files

### ISSUE THREAD

**Issue by thorade** [nschloe/betterbib#33]
My .bib file is under version control. It would be nice to have a quiet mode that does not print the error messages (or at least not to the file, maybe to stdout or some logfile instead). Then I could use betterbib to enhance just those entries that are indexed by Crossref. Also, in quiet mode do not add the `source = {CrossRef},` field.
Just a suggestion, does not have high priority. And thanks again for your script!

**Comment by thorade** [comment]
Thinking about it: What I really want to do is add DOIs where possible. No other changes.

**Comment by nschloe** [comment]
They are added if available from CrossRef. What else do you have in mind?

**Comment by thorade** [comment]
Yes, they are added and that is great! But some fileds are changed (e.g. `\"a` is changed to ä in title or author name), and the source field is added, and some comments are printed. But what if I only want to add DOIs and not change the file otherwise (umlauts will break my workflow, additional fields or comments would upset collaborators)? Currently, some manual steps are required. Not a problem, because the DOIs only need to be added once.
I do not know how this could be solved elegantly.

**Comment by nschloe** [comment]
So basically you'd like to keep everything, and only add the DOI when available? This use case seems a little too specific for including it into betterbib, but you can easily do it yourself. Basically I'd copy over `betterbib` to `add_doi` (or whatever you want to call it) and instead of writing the result of `pybtex_to_bibtex_string(result, bib_id)` to the output file, use the original `data` plus the DOI from `result`.
